import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { FuelTypeEnum } from 'src/common/enums/fuelType';
import { OrderStateEnum } from 'src/common/enums/orderState';
import { Category } from 'src/modules/categories/entities/category.entity';
import { Order } from 'src/modules/orders/entities/order.entity';
import { FuelType } from 'src/modules/truck-models/entities/fuel-type.entity';
import { Repository } from 'typeorm';



@Injectable()
export class OrderSeeder {
  constructor(
    @InjectRepository(Order) private orderRepository: Repository<Order>,
  ) {}

  async run() {
    await this.orderRepository.save([
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:1,
        fromHaveLift:1,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:3,
        toFloorNumber:4,
        state:OrderStateEnum.DRAFT,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:0,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:6,
        toFloorNumber:4,
        state:OrderStateEnum.DRAFT,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:1,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:3,
        toFloorNumber:4,
        state:OrderStateEnum.DRAFT,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:1,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:3,
        toFloorNumber:4,
        state:OrderStateEnum.CLOSED,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:1,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:3,
        toFloorNumber:4,
        state:OrderStateEnum.CLOSED,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:1,
        fromHaveLift:1,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:3,
        toFloorNumber:4,
        state:OrderStateEnum.SCHEDULED,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:1,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:3,
        toFloorNumber:4,
        state:OrderStateEnum.DRAFT,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:0,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:6,
        toFloorNumber:4,
        state:OrderStateEnum.DRAFT,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:0,
        fromHaveLift:0,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:6,
        toFloorNumber:4,
        state:OrderStateEnum.DRAFT,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
      {
        orderDateTime:'2025-07-15 10:35:00',
        fromPhoneNumber:'+9639999006600',
        toPhoneNumber:'+9639999006700',
        isScheduled:1,
        fromHaveLift:0,
        toHaveLift:1,
        needHolders:0,
        fromFloorNumber:6,
        toFloorNumber:4,
        state:OrderStateEnum.SCHEDULED,
        note:'',
        customer:{id:1},
        fromAddress:{id:1},
        toAddress:{id:2},
        vehicleType:{id:1},
        sizeType:{id:2},
        paymentType:{id:1},
      },
    ]);
  }
}
